insert into tabelaDePecas values	('AM01', 'Amortecedor Cabine', 350, 'Amortecedor', 'Em Estoque'),
									('AM02', 'Amortecedor Mala e Capô', 350, 'Amortecedor', 'Em Estoque'),
									('AM03', 'Amortecedor Suspensão', 350, 'Amortecedor', 'Em Estoque'),
									('AM04', 'Coxim, Batente e Coifa', 350, 'Amortecedor', 'Em Estoque'),
									('AM05', 'Mancal Amortecedor', 350, 'Amortecedor', 'Em Estoque'),
									('AM06', 'Kit Amortecedor', 350, 'Amortecedor', 'Em Estoque'),
									('AF01', 'Bomba de água', 170, 'Arrefecimento', 'Em Estoque'),
									('AF02', 'Intercooler', 170, 'Arrefecimento', 'Em Estoque'),
									('AF03', 'Mangueira', 170, 'Arrefecimento', 'Em Estoque'),
									('AF04', 'Radiador', 170, 'Arrefecimento', 'Em Estoque'),
									('AF05', 'Reservatório de Água', 170, 'Arrefecimento', 'Em Estoque'),
									('AF06', 'Válvula Termostática', 170, 'Arrefecimento', 'Em Estoque'),
									('AF07', 'Ventoinha', 170, 'Arrefecimento', 'Em Estoque'),
									('CM01', 'Compressor Ar Condicionado', 280, 'Climatização', 'Em Estoque'),
									('CM02', 'Filtro Ar Condicionado', 280, 'Climatização', 'Em Estoque'),
									('CM03', 'Kit Filtro Ar e Higienizador', 280, 'Climatização', 'Em Estoque'),
									('CR01', 'Correia Alternador', 1000, 'Correias', 'Em Estoque'),
									('CR02', 'Correia Dentada', 1000, 'Correias', 'Em Estoque'),
									('CR03', 'Kit Correia e Corrente', 1000, 'Correias', 'Em Estoque'),
									('CR04', 'Tensor e Polia', 1000, 'Correias', 'Em Estoque'),
									('DR01', 'Barra Axial', 1250, 'Direção', 'Em Estoque'),
									('DR02', 'Barra Direção', 1250, 'Direção', 'Em Estoque'),
									('DR03', 'Barra Estabilizadora', 1250, 'Direção', 'Em Estoque'),
									('DR04', 'Barra Reação', 1250, 'Direção', 'Em Estoque'),
									('DR05', 'Braço Auxiliar', 1250, 'Direção', 'Em Estoque'),
									('DR06', 'Braço Pitman', 1250, 'Direção', 'Em Estoque'),
									('DR07', 'Bomba Direção', 1250, 'Direção', 'Em Estoque'),
									('DR08', 'Caixa De Direção', 1250, 'Direção', 'Em Estoque'),
									('DR09', 'Coluna Direção', 1250, 'Direção', 'Em Estoque'),
									('DR10', 'Junta Elástica', 1250, 'Direção', 'Em Estoque'),
									('DR11', 'Morceguinho', 1250, 'Direção', 'Em Estoque'),
									('DR12', 'Pino', 1250, 'Direção', 'Em Estoque'),
									('DR13', 'Reparos', 1250, 'Direção', 'Em Estoque'),
									('DR14', 'Terminal Direção', 1250, 'Direção', 'Em Estoque'),
									('EB01', 'Atuador', 1500, 'Embreagem', 'Em Estoque'),
									('EB02', 'Cilindro Auxiliar', 1500, 'Embreagem', 'Em Estoque'),
									('EB03', 'Cabo Embreagem', 1500, 'Embreagem', 'Em Estoque'),
									('EB04', 'Cilindro Mestre', 1500, 'Embreagem', 'Em Estoque'),
									('EB05', 'Disco', 1500, 'Embreagem', 'Em Estoque'),
									('EB06', 'Garfo Embreagem', 1500, 'Embreagem', 'Em Estoque'),
									('EB07', 'Kit Embreagem', 1500, 'Embreagem', 'Em Estoque'),
									('EB08', 'Platô', 1500, 'Embreagem', 'Em Estoque'),
									('EB09', 'Rolamento', 1500, 'Embreagem', 'Em Estoque'),
									('EB10', 'Volante Motor', 1500, 'Embreagem', 'Em Estoque'),
									('FR01', 'Bloco Compressor', 2250, 'Freio', 'Em Estoque'),
									('FR02', 'Cilindro Mestre', 2250, 'Freio', 'Em Estoque'),
									('FR03', 'Cilindro Roda', 2250, 'Freio', 'Em Estoque'),
									('FR04', 'Disco Freio', 2250, 'Freio', 'Em Estoque'),
									('FR05', 'Filtro Apu', 2250, 'Freio', 'Em Estoque'),
									('FR06', 'Kit Freio', 2250, 'Freio', 'Em Estoque'),
									('FR07', 'Kit Pastilha E Disco', 2250, 'Freio', 'Em Estoque'),
									('FR08', 'Mangote Freio', 2250, 'Freio', 'Em Estoque'),
									('FR09', 'Pastilha Freio', 2250, 'Freio', 'Em Estoque'),
									('FR10', 'Pinça Freio', 2250, 'Freio', 'Em Estoque'),
									('FR11', 'Reparos', 2250, 'Freio', 'Em Estoque'),
									('FR12', 'Reservatório De Óleo', 2250, 'Freio', 'Em Estoque'),
									('FR13', 'Sapata Freio', 2250, 'Freio', 'Em Estoque'),
									('FR14', 'Sensor Abs', 2250, 'Freio', 'Em Estoque'),
									('FR15', 'Servo Freio', 2250, 'Freio', 'Em Estoque'),
									('FR16', 'Tambor Freio', 2250, 'Freio', 'Em Estoque'),
									('FR17', 'Válvulas', 2250, 'Freio', 'Em Estoque'),
									('MT01', 'Anel', 1800, 'Motor', 'Em Estoque'),
									('MT02', 'Atuador Marcha Lenta', 1800, 'Motor', 'Em Estoque'),
									('MT03', 'Bronzinas', 1800, 'Motor', 'Em Estoque'),
									('MT04', 'Bomba Óleo', 1800, 'Motor', 'Em Estoque'),
									('MT05', 'Cabeçote Motor', 1800, 'Motor', 'Em Estoque'),
									('MT06', 'Camisa Motor', 1800, 'Motor', 'Em Estoque'),
									('MT07', 'Carburador', 1800, 'Motor', 'Em Estoque'),
									('MT08', 'Cárter Motor', 1800, 'Motor', 'Em Estoque'),
									('MT09', 'Coxim Motor', 1800, 'Motor', 'Em Estoque'),
									('MT10', 'Eixo Comando', 1800, 'Motor', 'Em Estoque'),
									('MT11', 'Engrenagem Virabrequim', 1800, 'Motor', 'Em Estoque'),
									('MT12', 'Filtro Ar', 1800, 'Motor', 'Em Estoque'),
									('MT13', 'Filtro Combustível', 1800, 'Motor', 'Em Estoque'),
									('MT14', 'Filtro Óleo', 1800, 'Motor', 'Em Estoque'),
									('MT15', 'Filtro Separador', 1800, 'Motor', 'Em Estoque'),
									('MT16', 'Juntas', 1800, 'Motor', 'Em Estoque'),
									('MT17', 'Kit Filtros', 1800, 'Motor', 'Em Estoque'),
									('MT18', 'Kit Motor', 1800, 'Motor', 'Em Estoque'),
									('SP01', 'Bandeja Balança', 500, 'Suspensão', 'Em Estoque'),
									('SP02', 'Bieleta', 500, 'Suspensão', 'Em Estoque'),
									('SP03', 'Bolsa Ar Pneumática', 500, 'Suspensão', 'Em Estoque'),
									('SP04', 'Braço', 500, 'Suspensão', 'Em Estoque'),
									('SP05', 'Bucha Bandeja', 500, 'Suspensão', 'Em Estoque'),
									('SP06', 'Bucha Braço Oscilante', 500, 'Suspensão', 'Em Estoque'),
									('SP07', 'Bucha Braço Tensor', 500, 'Suspensão', 'Em Estoque'),
									('SP08', 'Bucha Braço Transversal', 500, 'Suspensão', 'Em Estoque'),
									('SP09', 'Bucha Eixo', 500, 'Suspensão', 'Em Estoque'),
									('SP10', 'Bucha Estabilizadora', 500, 'Suspensão', 'Em Estoque'),
									('TM01', 'Cabo Seletor Marcha', 450, 'Transmissão', 'Em Estoque'),
									('TM02', 'Coxim Câmbio', 450, 'Transmissão', 'Em Estoque'),
									('TM03', 'Junta Deslizante', 450, 'Transmissão', 'Em Estoque'),
									('TM04', 'Junta Homocinética', 450, 'Transmissão', 'Em Estoque'),
									('TM05', 'Kit Reparo Homocinética', 450, 'Transmissão', 'Em Estoque'),
									('TM06', 'Retentores', 450, 'Transmissão', 'Em Estoque'),
									('TM07', 'Rolamento Câmbio', 450, 'Transmissão', 'Em Estoque'),
									('TM08', 'Rolamento Roda', 450, 'Transmissão', 'Em Estoque'),
									('TM09', 'Semi Eixo', 450, 'Transmissão', 'Em Estoque'),
									('TM10', 'Trizeta', 450, 'Transmissão', 'Em Estoque'),
									('TM11', 'Tulipa', 450, 'Transmissão', 'Em Estoque'),
									('TM12', 'Componente Caixa De Marcha', 450, 'Transmissão', 'Em Estoque');
