insert into servicos values ('RP10', 'Revisão Periódica', 'Revisão 10K Km', 701),
							('RP20', 'Revisão Periódica', 'Revisão 20K Km', 702),
							('RP30', 'Revisão Periódica', 'Revisão 30K Km', 703),
							('RP40', 'Revisão Periódica', 'Revisão 40K Km', 704),
							('RP50', 'Revisão Periódica', 'Revisão 50K Km', 705),
							('MN01', 'Manutenção', 'Corretiva / Preventiva', 301),
							('MN02', 'Manutenção', 'Corretiva / Preventiva', 302),
							('MN03', 'Manutenção', 'Corretiva / Preventiva', 303),
							('MN04', 'Manutenção', 'Corretiva / Preventiva', 304),
							('MN05', 'Manutenção', 'Corretiva / Preventiva', 305),
							('MN06', 'Manutenção', 'Corretiva / Preventiva', 306),
							('MN07', 'Manutenção', 'Corretiva / Preventiva', 307),
							('MN08', 'Manutenção', 'Corretiva / Preventiva', 308),
							('MN09', 'Manutenção', 'Corretiva / Preventiva', 309),
							('MN10', 'Manutenção', 'Corretiva / Preventiva', 310);